# Generated by Django 5.1.1 on 2024-09-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_dateposted_post_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=models.CharField(max_length=100)),
        ),
    ]
